-- BEFORE COMMIT QUERY CHANGE TO VARCHAR FROM VARCHAR2
create table MSTADMIN
(
    MSTID     VARCHAR2(10) not null,
    MSTTAG    VARCHAR2(20),
    MSTNAMA   VARCHAR2(20),
    MSTPASS   VARCHAR2(20),
    MSTACTIVE smallint,
    MSTCREATE VARCHAR2(27),
    MSTMODIFY VARCHAR2(27),
    constraint PK_MSTADMIN primary key (MSTID)
);

create table MSTCAPACITY
(
    MSTTYPE smallint not null,
    MSTMAX  BIGINT,
    MSTCUR  BIGINT,
    constraint PK_MSTCAPACITY primary key (MSTTYPE)
);

create table MSTGATE
(
    MSTID     VARCHAR2(10) not null,
    MSTTYPE   smallint,
    MSTLOKASI VARCHAR2(50),
    MSTIPIN   VARCHAR2(20),
    MSTPRTIN  VARCHAR2(10),
    MSTISOUT  smallint,
    MSTIPOUT  VARCHAR2(20),
    MSTPRTOUT VARCHAR2(10),
    MSTISUHF  smallint,
    MSTIPUHF  VARCHAR2(20),
    MSTPRTUHF VARCHAR2(10),
    MSTTYCON  smallint,
    MSTIPCON  VARCHAR2(20),
    MSTPRTCON VARCHAR2(10),
    MSTACTIVE smallint,
    MSTCREATE VARCHAR2(27),
    MSTMODIFY VARCHAR2(27),
    MSTACCESS smallint,
    MSTTAMU   smallint,
    MSTKARY   smallint,
    MSTC1STAT smallint,
    MSTC1IPAD VARCHAR2(20),
    MSTC1URL  VARCHAR2(100),
    MSTC2STAT smallint,
    MSTC2IPAD VARCHAR2(20),
    MSTC2URL  VARCHAR2(100),
    MSTC3STAT smallint,
    MSTC3IPAD VARCHAR2(20),
    MSTC3URL  VARCHAR2(100),
    MSTC4STAT smallint,
    MSTC4IPAD VARCHAR2(20),
    MSTC4URL  VARCHAR2(100),
    constraint PK_MSTGATE primary key (MSTID)
);


create table MSTKARY
(
    MSTID     VARCHAR2(20) not null,
    MSTTAG    VARCHAR2(30),
    MSTNAMA1  VARCHAR2(20),
    MSTNAMA2  VARCHAR2(50),
    MSTJAB    VARCHAR2(50),
    MSTPASS   VARCHAR2(20),
    MSTACTIVE smallint,
    MSTCREATE VARCHAR2(27),
    MSTMODIFY VARCHAR2(27),
    MSTTMP1   VARCHAR2(2500),
    MSTTMP2   VARCHAR2(2500),
    MSTTMP3   VARCHAR2(2500),
    MSTTMP4   VARCHAR2(2500),
    MSTPOS    smallint,
    MSTPIC    smallint,
    MSTMANDOR VARCHAR2(50),
    MSTPOS2   smallint,
    MSTPOS3   smallint,
    MSTPOS4   smallint,
    MSTPOS5   smallint,
    MSTUNV    smallint,
    MSTVALID  DATE,
    MSTTARIP  numeric(15, 2),
    MSTPIC2   smallint,
    MSTTAG2   VARCHAR2(30),
    MSTTAG3   VARCHAR2(30),
    MSTTAG4   VARCHAR2(30),
    MSTTAG5   VARCHAR2(30),
    MSTTYPE1  smallint,
    MSTTYPE2  smallint,
    MSTTYPE3  smallint,
    constraint PK_MSTKARY primary key (MSTID)
);


create table MSTPERUSH
(
    MSTNAME   VARCHAR2(50) not null,
    MSTACTIVE smallint,
    MSTTYPE   smallint,
    MSTCREATE VARCHAR2(27),
    MSTMODIFY VARCHAR2(27),
    constraint PK_MSTPERUSH primary key (MSTNAME)
);


create table MSTTAMU
(
    MSTID     VARCHAR2(10) not null,
    MSTTAG    VARCHAR2(20),
    MSTNAMA   VARCHAR2(20),
    MSTPASS   VARCHAR2(20),
    MSTACTIVE smallint,
    MSTCREATE VARCHAR2(27),
    MSTMODIFY VARCHAR2(27),
    MSTPOS    smallint,
    constraint PK_MSTTAMU primary key (MSTID)
);


create table MSTTMP
(
    MSTID   VARCHAR2(20) not null,
    MSTTMP1 VARCHAR2(2500),
    MSTTMP2 VARCHAR2(2500),
    MSTTMP3 VARCHAR2(2500),
    MSTTMP4 VARCHAR2(2500),
    constraint PK_MSTTMP primary key (MSTID)
);
-- MSTUHFTAG definition
-- Drop table
-- DROP TABLE MSTUHFTAG;

create table MSTUHFTAG
(
    MSTID     VARCHAR2(10) not null,
    MSTTAG    VARCHAR2(30),
    MSTNAMA   VARCHAR2(20),
    MSTNOPOL  VARCHAR2(10),
    MSTJAB    VARCHAR2(50),
    MSTACTIVE smallint,
    MSTCREATE VARCHAR2(27),
    MSTMODIFY VARCHAR2(27),
    constraint PK_MSTUHFTAG primary key (MSTID)
);


create table SYSACCESS
(
    USID        VARCHAR2(10)        not null,
    USNAME      VARCHAR2(30),
    USPOS       VARCHAR2(30),
    USACCESS    VARCHAR2(256),
    USPASS      VARCHAR2(20),
    USACTIVE    smallint default 0 not null,
    CREATEDUSER VARCHAR2(10),
    CREATEDDATE TIMESTAMP NULL,
    UPDATEDUSER VARCHAR2(10),
    UPDATEDDATE TIMESTAMP NULL
);
-- SYSMENU definition
-- Drop table
-- DROP TABLE SYSMENU;

create table SYSMENU
(
    MENUID      INTEGER not null,
    MENUPOS     smallint,
    MENUGROUP   VARCHAR2(100),
    MENUCAPTION VARCHAR2(100),
    MENUSUB     VARCHAR2(100),
    MENUVISIBLE smallint default 0,
    MENUMAX     INTEGER,
    constraint PK_SYSMENU primary key (MENUID)
);
-- SYSNUMBERING definition
-- Drop table
-- DROP TABLE SYSNUMBERING;

create table SYSNUMBERING
(
    LASTNUMBER   INTEGER,
    LASTPOSITION VARCHAR2(5),
    LASTUSEDUSER VARCHAR2(10),
    LASTUSEDDATE TIMESTAMP,
    LASTMONTH    INTEGER,
    LASTYEAR     smallint
);


create table SYSPERIOD
(
    PERIODNUM         smallint           not null,
    PERIODNAME        VARCHAR2(50),
    PERIODSTART       TIMESTAMP NULL,
    PERIODEND         TIMESTAMP NULL,
    PERIODLOCK        TIMESTAMP NULL,
    PERIODCLOSED      smallint default 0 not null,
    PERIODCREATEDUSER VARCHAR2(10),
    PERIODCREATEDDATE TIMESTAMP NULL,
    PERIODUPDATEDUSER VARCHAR2(10),
    PERIODUPDATEDDATE TIMESTAMP NULL,
    PERIODCLOSEDUSER  VARCHAR2(10),
    PERIODCLOSEDDATE  TIMESTAMP NULL,
    PERIODOPENEDUSER  VARCHAR2(10),
    PERIODOPENEDDATE  TIMESTAMP NULL,
    PERIODFILENAME    VARCHAR2(50),
    constraint PK_SYSPERIOD primary key (PERIODNUM)
);
-- SYSPROFILE definition
-- Drop table
-- DROP TABLE SYSPROFILE;

create table SYSPROFILE
(
    KEYWORD     VARCHAR2(10),
    PROFILE     VARCHAR2(50),
    CREATEDDATE TIMESTAMP
);
-- TRNEXTLANG definition
-- Drop table
-- DROP TABLE TRNEXTLANG;

create table TRNEXTLANG
(
    TRNNO     BIGINT not null,
    TRNID     VARCHAR2(10),
    TRNTIME   TIMESTAMP,
    TRNMAN    VARCHAR2(20),
    TRNTYPE   smallint,
    TRNMTH    smallint,
    TRNIPL    numeric(15, 2),
    TRNTOTAL  numeric(15, 2),
    TRNCOST   numeric(15, 2),
    TRNSDATE  DATE,
    TRNEDATE  DATE,
    TRNREPORT smallint,
    TRNCR     VARCHAR2(27),
    constraint PK_TRNEXTLANG primary key (TRNNO)
);


create table TRNGENLOG
(
    TRNLOG   TIMESTAMP,
    TRNID    VARCHAR2(20),
    TRNTYPE  smallint,
    TRNGATE  VARCHAR2(10),
    TRNINOUT smallint
);


create table TRNGENLOGV
(
    TRNLOG  TIMESTAMP,
    TRNID   VARCHAR2(20),
    TRNGATE VARCHAR2(10),
    TRNPOS  VARCHAR2(10),
    TRNNAMA VARCHAR2(20),
    TRNTAMU VARCHAR2(20)
);


create table TRNKRTLANG
(
    TRNID      VARCHAR2(10) not null,
    TRNCARDNO  smallint,
    TRNTIMEIN  TIMESTAMP NULL,
    TRNGATEIN  VARCHAR2(10),
    TRNCEKOUT  smallint,
    TRNTIMEOUT TIMESTAMP NULL,
    TRNGATEOUT VARCHAR2(10)
);


create table TRNKRTTAMU
(
    TRNID      VARCHAR2(10) not null,
    TRNTIMEIN  TIMESTAMP NULL,
    TRNGATEIN  VARCHAR2(10),
    TRNCEKOUT  smallint,
    TRNTIMEOUT TIMESTAMP NULL,
    TRNGATEOUT VARCHAR2(10)
);


create table TRNOFFLINE
(
    TRNLOG  VARCHAR2(50) not null,
    TRNTAG  VARCHAR2(20),
    TRNGATE VARCHAR2(10),
    TRNTIME TIMESTAMP,
    TRNTYPE smallint,
    constraint PK_TRNOFFLINE primary key (TRNLOG)
);


create table TRNSYSLOG
(
    TRNLOG TIMESTAMP,
    TRNACT VARCHAR2(20),
    TRNPOS smallint,
    TRNID  VARCHAR2(20),
    TRNOLD VARCHAR2(1024),
    TRNUSR VARCHAR2(27)
);


create table TRNTAMU
(
    TRNID     VARCHAR2(10) not null,
    TRNKARTU  VARCHAR2(10),
    TRNNAMA   VARCHAR2(50),
    TRNINST   VARCHAR2(50),
    TRNKEPR   VARCHAR2(50),
    TRNJUML   smallint,
    TRNEXPD   DATE,
    TRNNOTE   VARCHAR2(1024),
    TRNLIST   VARCHAR2(1024),
    TRNBLOCK  smallint,
    TRNACTIVE smallint,
    TRNCREATE VARCHAR2(27),
    TRNMODIFY VARCHAR2(27),
    TRNFCO    smallint,
    TRNBLK    smallint,
    constraint PK_TRNTAMU primary key (TRNID)
);

CREATE TABLE PIC001
(
    PLOG  TIMESTAMP,
    PID   VARCHAR2(20),
    PTYPE VARCHAR2(15),
    PDATA LONGBLOB
);

CREATE TABLE PIC002
(
    PLOG  TIMESTAMP,
    PID   VARCHAR2(20),
    PTYPE VARCHAR2(15),
    PDATA LONGBLOB
);

CREATE TABLE PIC003
(
    PLOG  TIMESTAMP,
    PID   VARCHAR2(20),
    PTYPE VARCHAR2(15),
    PDATA LONGBLOB
);

CREATE TABLE PIC004
(
    PLOG  TIMESTAMP,
    PID   VARCHAR2(20),
    PTYPE VARCHAR2(15),
    PDATA LONGBLOB
);

CREATE TABLE PIC005
(
    PLOG  TIMESTAMP,
    PID   VARCHAR2(20),
    PTYPE VARCHAR2(15),
    PDATA LONGBLOB
);

CREATE TABLE PIC006
(
    PLOG  TIMESTAMP,
    PID   VARCHAR2(20),
    PTYPE VARCHAR2(15),
    PDATA LONGBLOB
);

CREATE TABLE PIC007
(
    PLOG  TIMESTAMP,
    PID   VARCHAR2(20),
    PTYPE VARCHAR2(15),
    PDATA LONGBLOB
);

CREATE TABLE PIC008
(
    PLOG  TIMESTAMP,
    PID   VARCHAR2(20),
    PTYPE VARCHAR2(15),
    PDATA LONGBLOB
);

